AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Metrics/LineLength:
  Exclude:
    - 'spec/spec_helper.rb'
  Max: 100

Style/Documentation:
  Enabled: false

Metrics/ParameterLists:
  Exclude:
    - 'lib/sbrf_merchant/api/client.rb'
