sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=9735ef84689218db8e96c19956062b07b3f300af987cfb6817765cc12c542c97
language: ruby
rvm:
  - 2.5.1
before_install:
  - gem install bundler -v 1.16.5 --no-document
  - gem install rubocop --no-document
notifications:
  - false
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
scripts:
  - rubocop
  - rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
